# Generated by Django 6.0.7 on 2026-08-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_alter_product_quantity_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
